# Generated by Django 4.0.5 on 2022-06-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiPrimerMVTApp', '0004_familiares_delete_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='relacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Papá'), (2, 'Mamá'), (3, 'Hermano'), (4, 'Hermana'), (5, 'Tío'), (6, 'Tía'), (7, 'Abuelo'), (8, 'Abuela'), (9, 'Primo'), (10, 'Prima')], verbose_name='Relación'),
        ),
    ]
