# Generated by Django 4.0.5 on 2022-06-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiPrimerMVTApp', '0005_alter_familiares_relacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('relacion', models.PositiveSmallIntegerField(choices=[(1, 'Papá'), (2, 'Mamá'), (3, 'Hermano'), (4, 'Hermana'), (5, 'Tío'), (6, 'Tía'), (7, 'Abuelo'), (8, 'Abuela'), (9, 'Primo'), (10, 'Prima')], verbose_name='Relación')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('fecha', models.DateField(verbose_name='Fecha Nacimiento')),
            ],
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
